language: ruby
sudo: false
before_install:
  - rm Gemfile.lock || true
bundler_args: --without development
script:
  - "bundle exec rake spec"
notifications:
  email: true
rvm:
  - 2.3.0-dev
  - 2.2.4
  - 2.1.7
  - 2.0.0
  - 1.9.3

env:
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION=">= 4.4.0" # should be latest?

matrix:
  exclude:
    - rvm: 2.3.0-dev
      env: PUPPET_VERSION="~> 3.5.0"
    - rvm: 2.2.4
      env: PUPPET_VERSION="~> 3.5.0"
    - rvm: 2.1.7
      env: PUPPET_VERSION="~> 3.5.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.5.0"
